# Site settings
title: hklee blog
email: lulu.hklee002@gmail.com
baseurl: "/lulu-hklee"

github_username: hklee002

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

  highlighter: pygments

permalink: pretty

safe: true
lsi: true
